title: State Courts Practice Directions
remote_theme: opengovsg/opendoc-theme
section_order:
  - State Courts Practice Directions
  - "Part I: Introduction"
  - "Part II: Originating Processes and Documents"
  - "Part III: Simplified Process for Civil Proceedings in the Magistrate’s Court"
  - "Part IV: Interlocutory and other Applications"
  - "Part V: Hearings via Skype"
  - "Part VI: Alternative Dispute Resolution"
  - "Part VII: Discovery and Inspection of Electronically Stored Documents"
  - "Part VIII: Evidence – Witnesses, Affidavits and Exhibits"
  - "Part IX: Fixing of Matters for Hearing"
  - "Part X: Documents and Authorities for use in Court"
  - "Part XI: Judgements and Orders"
  - "Part XII: Appeals"
  - "Part XIII: Electronic Filing Service"
  - "Part XIV: Execution Matters"
elastic_search:
  index: intro_index
  doctype: bare
environment: DEV
google_analytics: UA-113717369-6
server_LOCAL: https://search.opendoc.sg
server_DEV: https://search.opendoc.sg
styling_options:
  primary_brand_color: '#9f0836'
  logo_path: /assets/logo-full.png
  opendoc_logo_path: /assets/images/logo-full.png
